# Generated by Django 3.2.7 on 2021-09-05 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_auto_20210905_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='location',
            field=models.ManyToManyField(to='photos.Location'),
        ),
        migrations.AddField(
            model_name='category',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='photos.photo'),
        ),
    ]
