# Generated by Django 3.2.7 on 2021-09-05 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_auto_20210905_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='location',
        ),
        migrations.RemoveField(
            model_name='category',
            name='photo',
        ),
        migrations.AddField(
            model_name='photo',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='photos.category'),
        ),
    ]
